global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
    - targets: ['host.docker.internal:9090']
  
  - job_name: 'node-exporter'
    scrape_interval: 1m
    static_configs:
    - targets: ['host.docker.internal:9100']