version: '3'
services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ./jenkins_docker_certs:/certs/client
      - ./jenkins_home:/var/jenkins_home
    restart: always
    ports:
      - "2376:2376"
    networks:
      - jenkins
    command: --storage-driver overlay2
  
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8088:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://jenkins-docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_CERT_VERIFY=1
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins_docker_certs:/certs/client:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins-docker
    restart: always

networks:
  jenkins:
    driver: bridge
